services:
  authjs-docker-test:
    build: .
    environment:
      - AUTH_GOOGLE_ID
      - AUTH_GOOGLE_SECRET
      - AUTH_SECRET="MohY0/2zSQw/psWEnejC2ka3Al0oifvY4YjOkUaFfnI="
      - AUTH_URL=http://localhost:3000/auth
    ports:
      - "3000:3000"
